

set(QUAZIP_DEBUG_POSTFIX "_debug")
set(QUAZIP_RELWITHDEBINFO_POSTFIX "_relWithDebInfo")


if(__QuaZip_BUILD_LIB)
    set(CMAKE_DEBUG_POSTFIX ${QUAZIP_DEBUG_POSTFIX})
    set(CMAKE_RELWITHDEBINFO_POSTFIX ${QUAZIP_RELWITHDEBINFO_POSTFIX})
endif()